// AUTOGENERATED - DO NOT EDIT
#include <jni.h>
#include <cstddef>
#include <algorithm>
#include <string>
#include "native/ICompressionInternal_exports.h"

// JNI requires global state because the VM reference must be captured at load time.
// JNI_OnLoad() is called when the shared library is loaded; we save the JavaVM pointer
// so that native threads can attach themselves later (see ScopedEnv below).
static JavaVM* g_vm = nullptr;

// Cached Java class/method references for callbacks into GML.
// These are resolved once at init time and reused (JNI method lookups are expensive).
static jclass g_bridgeClass = nullptr;
static jmethodID g_mid_GetExtensionOption = nullptr;

// JNI_OnLoad is called automatically when System.loadLibrary() occurs.
// This is our one chance to capture the VM pointer before any other JNI calls.
extern "C" jint JNI_OnLoad(JavaVM* vm, void*) { g_vm = vm; return JNI_VERSION_1_6; }

static void throwIAE(JNIEnv* env, const char* msg) {
    jclass iae = env->FindClass("java/lang/IllegalArgumentException");
    if (iae) env->ThrowNew(iae, msg);
}

// ScopedEnv: RAII wrapper for JNIEnv* that handles thread attachment.
// Native threads that weren't created by the JVM must call AttachCurrentThread
// before making any JNI calls. This struct does it automatically in ctor,
// and DetachCurrentThread in dtor. Main thread doesn't need attach (GetEnv succeeds).
struct ScopedEnv {
    JNIEnv* env = nullptr;
    bool detach = false;

    ScopedEnv() {
        if (!g_vm) return;
        jint rc = g_vm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6);
        if (rc == JNI_OK) return;  // Already attached (main thread case)
        if (rc == JNI_EDETACHED && g_vm->AttachCurrentThread(&env, nullptr) == JNI_OK) {
            detach = true;  // We attached, so we must detach in dtor
        } else {
            env = nullptr;  // Failed to attach
        }
    }

    ~ScopedEnv() {
        if (detach) g_vm->DetachCurrentThread();
    }
};

// UtfChars: RAII wrapper for JNI string pinning.
// GetStringUTFChars returns a temporary C-string pointer that MUST be released
// via ReleaseStringUTFChars when done. This struct ensures proper cleanup.
// Without this, we'd leak JNI local refs and potentially crash on ref table overflow.
struct UtfChars {
    JNIEnv* env; jstring s; const char* p;
    UtfChars(JNIEnv* e, jstring js) : env(e), s(js), p(js ? e->GetStringUTFChars(js, nullptr) : nullptr) {}
    ~UtfChars() { if (s && p) env->ReleaseStringUTFChars(s, p); }
    const char* c_str() const { return p; }
};

static const char* __JNI_JAVA__GetExtensionOption(const char* extName, const char* optName)
{
    thread_local std::string tls_result;
    tls_result.clear();

    ScopedEnv scoped;
    if (!g_bridgeClass || !g_mid_GetExtensionOption) {
        return nullptr;
    }

    JNIEnv* env = scoped.env;

    jstring jExtName = extName ? env->NewStringUTF(extName) : nullptr;
    jstring jOptName = optName ? env->NewStringUTF(optName) : nullptr;

    jstring jRet = static_cast<jstring>(
        env->CallStaticObjectMethod(g_bridgeClass, g_mid_GetExtensionOption, jExtName, jOptName)
    );

    if (jExtName) env->DeleteLocalRef(jExtName);
    if (jOptName) env->DeleteLocalRef(jOptName);

    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
        if (jRet) env->DeleteLocalRef(jRet);
        return nullptr;
    }

    if (!jRet) {
        return nullptr;
    }

    const char* chars = env->GetStringUTFChars(jRet, nullptr);
    if (!chars) {
        env->DeleteLocalRef(jRet);
        return nullptr;
    }

    tls_result.assign(chars);

    env->ReleaseStringUTFChars(jRet, chars);
    env->DeleteLocalRef(jRet);

    return tls_result.c_str();
}
static void __JNI_InitExtUtils()
{
    gm::details::GMRTRunnerInterface runner{};
    runner.ExtOptGetString = __JNI_JAVA__GetExtensionOption;
    gm::ExtUtils::Init(runner);
}
// __ICompression_queue_buffer JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__ICompression_queue_buffer(JNIEnv* env, jclass /* ICompressionBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }

    double __ret = __EXT_NATIVE__ICompression_queue_buffer((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}
// ic_compress JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__ic_compress_491F2999B80A(JNIEnv* env, jclass /* ICompressionBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__ic_compress((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// ic_decompress JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__ic_decompress_13D9AD60AA5C(JNIEnv* env, jclass /* ICompressionBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__ic_decompress((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// ic_compress_file JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__ic_compress_file_AD1A0B186DD3(JNIEnv* env, jclass /* ICompressionBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__ic_compress_file((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// ic_decompress_file JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__ic_decompress_file_4F7CFC3C5862(JNIEnv* env, jclass /* ICompressionBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__ic_decompress_file((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// ic_compress_buf JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__ic_compress_buf_A330A9927BE3(JNIEnv* env, jclass /* ICompressionBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__ic_compress_buf((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// ic_decompress_buf JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__ic_decompress_buf_12C5FCD9503E(JNIEnv* env, jclass /* ICompressionBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__ic_decompress_buf((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// ic_list JNI wrapper signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__ic_list_A2354835A2BC(JNIEnv* env, jclass /* ICompressionBridge */, jstring archive, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    UtfChars __pin_archive(env, archive);
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__ic_list((char *)__pin_archive.c_str(), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// ic_extract JNI wrapper signature: (Ljava/lang/String;Ljava/lang/String;Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__ic_extract_6495A048B490(JNIEnv* env, jclass /* ICompressionBridge */, jstring archive, jstring output_dir, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    UtfChars __pin_archive(env, archive);
    UtfChars __pin_output_dir(env, output_dir);
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__ic_extract((char *)__pin_archive.c_str(), (char *)__pin_output_dir.c_str(), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// ic_extract_file JNI wrapper signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)D
static jdouble __JNI_WRAPPER__ic_extract_file_CD8EB142E95B(JNIEnv* env, jclass /* ICompressionBridge */, jstring archive, jstring entry, jstring output)
{
    UtfChars __pin_archive(env, archive);
    UtfChars __pin_entry(env, entry);
    UtfChars __pin_output(env, output);
    double __ret = __EXT_NATIVE__ic_extract_file((char *)__pin_archive.c_str(), (char *)__pin_entry.c_str(), (char *)__pin_output.c_str());
    return static_cast<jdouble>(__ret);
}

// ic_extract_mem JNI wrapper signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
static jstring __JNI_WRAPPER__ic_extract_mem_A65A2C8A548A(JNIEnv* env, jclass /* ICompressionBridge */, jstring archive, jstring entry)
{
    UtfChars __pin_archive(env, archive);
    UtfChars __pin_entry(env, entry);
    const char* __out = __EXT_NATIVE__ic_extract_mem((char *)__pin_archive.c_str(), (char *)__pin_entry.c_str());
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// ic_create JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__ic_create_29766E4370F3(JNIEnv* env, jclass /* ICompressionBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__ic_create((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// ic_add_file JNI wrapper signature: (DLjava/lang/String;Ljava/lang/String;)D
static jdouble __JNI_WRAPPER__ic_add_file_2DB179668414(JNIEnv* env, jclass /* ICompressionBridge */, jdouble handle, jstring path, jstring entry)
{
    UtfChars __pin_path(env, path);
    UtfChars __pin_entry(env, entry);
    double __ret = __EXT_NATIVE__ic_add_file(static_cast<double>(handle), (char *)__pin_path.c_str(), (char *)__pin_entry.c_str());
    return static_cast<jdouble>(__ret);
}

// ic_add_data JNI wrapper signature: (DLjava/lang/String;Ljava/lang/String;)D
static jdouble __JNI_WRAPPER__ic_add_data_0D72C44CA369(JNIEnv* env, jclass /* ICompressionBridge */, jdouble handle, jstring entry, jstring data)
{
    UtfChars __pin_entry(env, entry);
    UtfChars __pin_data(env, data);
    double __ret = __EXT_NATIVE__ic_add_data(static_cast<double>(handle), (char *)__pin_entry.c_str(), (char *)__pin_data.c_str());
    return static_cast<jdouble>(__ret);
}

// ic_close JNI wrapper signature: (D)D
static jdouble __JNI_WRAPPER__ic_close_122B140656E4(JNIEnv* /* env */, jclass /* ICompressionBridge */, jdouble handle)
{
    double __ret = __EXT_NATIVE__ic_close(static_cast<double>(handle));
    return static_cast<jdouble>(__ret);
}

// ic_detect JNI wrapper signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__ic_detect_F3147215D7E5(JNIEnv* env, jclass /* ICompressionBridge */, jstring data, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    UtfChars __pin_data(env, data);
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__ic_detect((char *)__pin_data.c_str(), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// ic_detect_file JNI wrapper signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__ic_detect_file_C85311AD0608(JNIEnv* env, jclass /* ICompressionBridge */, jstring path, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    UtfChars __pin_path(env, path);
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__ic_detect_file((char *)__pin_path.c_str(), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// ic_from_ext JNI wrapper signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__ic_from_ext_EC7E2E246F69(JNIEnv* env, jclass /* ICompressionBridge */, jstring name, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    UtfChars __pin_name(env, name);
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__ic_from_ext((char *)__pin_name.c_str(), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// ic_to_str JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__ic_to_str_2B500AD6233B(JNIEnv* env, jclass /* ICompressionBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__ic_to_str((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// nativeRegister(Class callbackClass): cache callback + register all JNI wrappers
extern "C" {
    JNIEXPORT void JNICALL Java_com_gamemaker_ExtensionCore_ExtBridge_ICompressionBridge_nativeRegister(JNIEnv* env, jclass bridgeClass)
    {
        if (!g_bridgeClass) {
            g_bridgeClass = static_cast<jclass>(env->NewGlobalRef(bridgeClass));
        }

        if (!g_mid_GetExtensionOption) {
            g_mid_GetExtensionOption = env->GetStaticMethodID(
                g_bridgeClass,
                "__EXT_JAVA__GetExtensionOption",
                "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;"
            );
            if (!g_mid_GetExtensionOption) {
                throwIAE(env, "Failed to bind __EXT_JAVA__GetExtensionOption");
                return;
            }
        }

        static bool g_extUtilsInitialized = false;
        if (!g_extUtilsInitialized) {
            __JNI_InitExtUtils();
            g_extUtilsInitialized = true;
        }

        // Registers all the native methods
        static const JNINativeMethod methods[] = {
            { "__EXT_JNI__ICompression_queue_buffer", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__ICompression_queue_buffer },
            { "__EXT_JNI__ic_compress", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__ic_compress_491F2999B80A },
            { "__EXT_JNI__ic_decompress", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__ic_decompress_13D9AD60AA5C },
            { "__EXT_JNI__ic_compress_file", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__ic_compress_file_AD1A0B186DD3 },
            { "__EXT_JNI__ic_decompress_file", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__ic_decompress_file_4F7CFC3C5862 },
            { "__EXT_JNI__ic_compress_buf", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__ic_compress_buf_A330A9927BE3 },
            { "__EXT_JNI__ic_decompress_buf", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__ic_decompress_buf_12C5FCD9503E },
            { "__EXT_JNI__ic_list", "(Ljava/lang/String;Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__ic_list_A2354835A2BC },
            { "__EXT_JNI__ic_extract", "(Ljava/lang/String;Ljava/lang/String;Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__ic_extract_6495A048B490 },
            { "__EXT_JNI__ic_extract_file", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)D", (void*)__JNI_WRAPPER__ic_extract_file_CD8EB142E95B },
            { "__EXT_JNI__ic_extract_mem", "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;", (void*)__JNI_WRAPPER__ic_extract_mem_A65A2C8A548A },
            { "__EXT_JNI__ic_create", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__ic_create_29766E4370F3 },
            { "__EXT_JNI__ic_add_file", "(DLjava/lang/String;Ljava/lang/String;)D", (void*)__JNI_WRAPPER__ic_add_file_2DB179668414 },
            { "__EXT_JNI__ic_add_data", "(DLjava/lang/String;Ljava/lang/String;)D", (void*)__JNI_WRAPPER__ic_add_data_0D72C44CA369 },
            { "__EXT_JNI__ic_close", "(D)D", (void*)__JNI_WRAPPER__ic_close_122B140656E4 },
            { "__EXT_JNI__ic_detect", "(Ljava/lang/String;Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__ic_detect_F3147215D7E5 },
            { "__EXT_JNI__ic_detect_file", "(Ljava/lang/String;Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__ic_detect_file_C85311AD0608 },
            { "__EXT_JNI__ic_from_ext", "(Ljava/lang/String;Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__ic_from_ext_EC7E2E246F69 },
            { "__EXT_JNI__ic_to_str", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__ic_to_str_2B500AD6233B },
        };

        env->RegisterNatives(bridgeClass, methods, sizeof(methods)/sizeof(methods[0]));
    }
}
